port: 7880
bind_addresses:
  - 0.0.0.0
rtc:
  tcp_port: 7881
  port_range_start: 50000
  port_range_end: 60000
  use_external_ip: true
  enable_loopback_candidate: false
redis:
  address: redis:6379
  username: ''
  password: ''
  db: 0
  use_tls: false
  sentinel_master_name: ''
  sentinel_username: ''
  sentinel_password: ''
  sentinel_addresses: []
  cluster_addresses: []
  max_redirects: null
turn:
  enabled: true
  domain: turn_server_name
  tls_port: 5349
  udp_port: 3478
  external_tls: true
  tls_cert: /etc/livekit/certs/livekit.crt
  tls_key: /etc/livekit/certs/livekit.key
  secret: ''
  user_lifetime: 24h
keys:
  server_key: server_secret
logging:
  json: false
  level: info
